service: arce-serverless-api

custom:
  secrets: ${file(secrets_conf.json)}


provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: eu-central-1
  environment: 
    JWT_SECRET: ${self:custom.secrets.JWT_SECRET}
    DB: ${self:custom.secrets.DB}

plugins:
  - serverless-offline

functions:

  verify-token:
    handler: auth/VerifyToken.auth

  login:
    handler: auth/AuthHandler.login
    events:
      - http:
          path: login
          method: post
          cors: true

  register: 
    handler: auth/AuthHandler.register
    events:
      - http:
          path: register
          method: post
          cors: true


  saveProfile:
    handler: user/UserHandler.saveProfile
    events:
      - http:
          path: profile
          method: post
          cors: true
          authorizer: verify-token

  updateProfile:
    handler: user/UserHandler.updateProfile
    events:
      - http:
          path: profile
          method: put
          cors: true
          authorizer: verify-token

  getProfile:
    handler: user/UserHandler.getProfile
    events:
      - http:
          path: profile
          method: get
          cors: true
          authorizer: verify-token

  saveLocation:
    handler: location/LocationHandler.saveLocation
    events:
      - http: 
          path: location/{id}
          method: post
          cors: true
          authorizer: verify-token

  getLocation:
    handler: location/LocationHandler.getLocation
    events:
      - http: 
          path: location/{id}
          method: get
          cors: true
          authorizer: verify-token

  newpwd:
    handler: account/AccountHandler.newPwd
    events:
      - http:
          path: account/newpwd
          method: put
          cors: true
          authorizer: verify-token

  resetpwd:
    handler: account/AccountHandler.resetPwd
    events:
      - http:
          path: account/reset_password
          method: post
          cors: true

  deleteAccount:
    handler: account/AccountHandler.delete
    events:
      - http:
          path: account/delete
          method: delete
          cors: true
          authorizer: verify-token

  saveExercises:
    handler: user/ExerciseHandler.saveExercise
    events:
      - http:
          path: my/exercises
          method: post
          cors: true
          authorizer: verify-token

  getExercises:
    handler: user/ExerciseHandler.getExercise
    events:
      - http:
          path: my/exercises
          method: get
          cors: true
          authorizer: verify-token

